version: "3"

services:
    sig.api:
        build:
            context: ./src/sig-api/vendor/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '1000'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8080:80'
            # - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: 'sail'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - './src/sig-api/:/var/www/html'
            
    sig.front:
        build: ./src/sig-front/
        volumes:
            - ./src/sig-front/:/var/www/html/
        ports:
            - 80:80

volumes:
    data:
